In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('kruskals_results.csv')
df

      Size  Seed MatrixOrList       Time
0       20   0.4         list   0.000994
1       20   0.4         list   0.000909
2       20   0.4         list   0.000754
3       20   0.4         list   0.000989
4       20   0.5         list   0.001264
...    ...   ...          ...        ...
1995   200   0.8       matrix  18.990012
1996   200   0.8       matrix  19.140806
1997   200   0.8       matrix  19.036733
1998   200   0.8       matrix  19.021666
1999   200   0.8       matrix  19.101084

[2000 rows x 4 columns]

In [3]:
list_filter = df['MatrixOrList'] == 'list'
list_df = df[list_filter]
list_df

     Size  Seed MatrixOrList       Time
0      20   0.4         list   0.000994
1      20   0.4         list   0.000909
2      20   0.4         list   0.000754
3      20   0.4         list   0.000989
4      20   0.5         list   0.001264
..    ...   ...          ...        ...
995   200   0.8         list  19.155974
996   200   0.8         list  19.178775
997   200   0.8         list  19.351835
998   200   0.8         list  19.101370
999   200   0.8         list  19.282757

[1000 rows x 4 columns]

In [4]:
grouped_list_df = list_df.groupby(['Size', 'Seed'])
average_time_list_df = grouped_list_df['Time'].median()
average_time_list_df

Size  Seed
20    0.4      0.000921
      0.5      0.001288
      0.6      0.001513
      0.7      0.001909
      0.8      0.002138
40    0.4      0.014995
      0.5      0.019338
      0.6      0.023738
      0.7      0.028510
      0.8      0.032545
60    0.4      0.076341
      0.5      0.101141
      0.6      0.120947
      0.7      0.141886
      0.8      0.161391
80    0.4      0.244296
      0.5      0.305154
      0.6      0.375749
      0.7      0.439250
      0.8      0.505249
100   0.4      0.586744
      0.5      0.748641
      0.6      0.906469
      0.7      1.064110
      0.8      1.226608
120   0.4      1.227970
      0.5      1.553325
      0.6      1.865304
      0.7      2.193806
      0.8      2.523208
140   0.4      2.278437
      0.5      2.861761
      0.6      3.463120
      0.7      4.063955
      0.8      4.664853
160   0.4      3.898561
      0.5      4.888433
      0.6      5.898865
      0.7      6.930703
      0.8      7.965150
180   0.4      6.247750
      0.5      7.819851
      0.6      9.474199
      0.7     11.020131
      0.8     12.654060
200   0.4      9.505913
      0.5     11.943541
      0.6     14.379138
      0.7     16.858750
      0.8     19.227645
Name: Time, dtype: float64

In [5]:
matrix_filter = df['MatrixOrList'] == 'matrix'
matrix_df = df[matrix_filter]
matrix_df

      Size  Seed MatrixOrList       Time
1000    20   0.4       matrix   0.000936
1001    20   0.4       matrix   0.000828
1002    20   0.4       matrix   0.000915
1003    20   0.4       matrix   0.000653
1004    20   0.4       matrix   0.001043
...    ...   ...          ...        ...
1995   200   0.8       matrix  18.990012
1996   200   0.8       matrix  19.140806
1997   200   0.8       matrix  19.036733
1998   200   0.8       matrix  19.021666
1999   200   0.8       matrix  19.101084

[1000 rows x 4 columns]

In [8]:
grouped_matrix_df = matrix_df.groupby(['Size', 'Seed'])
average_time_matrix_df = grouped_matrix_df['Time'].median()
average_time_matrix_df

Size  Seed
20    0.4      0.000914
      0.5      0.001259
      0.6      0.001555
      0.7      0.001840
      0.8      0.002154
40    0.4      0.015238
      0.5      0.019436
      0.6      0.024661
      0.7      0.029789
      0.8      0.033720
60    0.4      0.076595
      0.5      0.097885
      0.6      0.118800
      0.7      0.140004
      0.8      0.161471
80    0.4      0.244746
      0.5      0.311427
      0.6      0.374926
      0.7      0.440266
      0.8      0.501968
100   0.4      0.590436
      0.5      0.743456
      0.6      0.900433
      0.7      1.058551
      0.8      1.217694
120   0.4      1.223911
      0.5      1.548733
      0.6      1.863620
      0.7      2.190765
      0.8      2.516037
140   0.4      2.274805
      0.5      2.871398
      0.6      3.467736
      0.7      4.080358
      0.8      4.667629
160   0.4      3.880196
      0.5      4.878780
      0.6      5.900046
      0.7      6.912743
      0.8      7.866913
180   0.4      6.134473
      0.5      7.781229
      0.6      9.333197
      0.7     10.939685
      0.8     12.514295
200   0.4      9.377743
      0.5     11.819292
      0.6     14.259583
      0.7     16.577036
      0.8     19.021443
Name: Time, dtype: float64